export const icons = [
  { src: '/icons/javascript.svg', label: 'JavaScript' },
  { src: '/icons/react.svg', label: 'React' },
  { src: '/icons/python.svg', label: 'Python' },
  { src: '/icons/django.svg', label: 'Django' },
  { src: '/icons/next-js.svg', label: 'NextJS' },
  { src: '/icons/styled-components.svg', label: 'Styled Components' },
  { src: '/icons/postgresql.svg', label: 'PostgreSQL' },
  { src: '/icons/aws.svg', label: 'AWS' },
  { src: '/icons/docker.svg', label: 'Docker' },
  { src: '/icons/node-js.svg', label: 'Node' },
  { src: '/icons/pytest.svg', label: 'Pytest' },
  { src: '/icons/jest.svg', label: 'Jest' },
  { src: '/icons/react-testing-library.svg', label: 'RTL' },
  { src: '/icons/html5.svg', label: 'HTML' },
  { src: '/icons/css3.svg', label: 'CSS' },
];
